[[ZenohC]]
arch = "aarch64"
git-tree-sha1 = "0d406f9bef7a032195ed1120f24f5c45da2db7df"
os = "macos"

    [[ZenohC.download]]
    sha256 = "af2f7011462dc915124eb53a80a01709ef977bd790d33fc335a8cf27c4bee043"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.aarch64-apple-darwin.tar.gz"
[[ZenohC]]
arch = "aarch64"
git-tree-sha1 = "ebbf559d9d3eef63f432236211819560d6a41118"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "c7febc1e973dd160ff60884cffdf454eef20f58cc9a06bba90ffa956c2418dc6"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.aarch64-linux-gnu.tar.gz"
[[ZenohC]]
arch = "aarch64"
git-tree-sha1 = "66a92f4c35d516077cbc01b0db68b7403a54fea7"
libc = "musl"
os = "linux"

    [[ZenohC.download]]
    sha256 = "08b20fa022515e2cf1e1cfb7d4c4bcbafac04fd60139a6ff83c1ccd6b088cb53"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.aarch64-linux-musl.tar.gz"
[[ZenohC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8e62b5f2ce2cefd488bddad3a4acd9387fa51374"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "6bd575e8b675189df1963b876f806f665d54696b8014c4e22a0e65f66046f3bc"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.armv6l-linux-gnueabihf.tar.gz"
[[ZenohC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4620b3d13792542d27167dfb45bacabcf13a60c2"
libc = "musl"
os = "linux"

    [[ZenohC.download]]
    sha256 = "63f20028f96618780f3f10cd97a67b863b75907f3474c210376c65f1ddd3c9b3"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.armv6l-linux-musleabihf.tar.gz"
[[ZenohC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "08e181bb22af1c69f8657e5e853bc413178711cd"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "59175db0765b6d92740183768c1d79f4f3805a71b7c7eccf8f2e3cca8e83793b"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.armv7l-linux-gnueabihf.tar.gz"
[[ZenohC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6893bd21e5357ea0d52f0b0ba3fc9fa6c336b298"
libc = "musl"
os = "linux"

    [[ZenohC.download]]
    sha256 = "04d6cd31e83612a20d39701f3b27ddd754351a2f7f4a47b558c4ead21a475788"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.armv7l-linux-musleabihf.tar.gz"
[[ZenohC]]
arch = "i686"
git-tree-sha1 = "19825286dc61daaae1c8085168442058cfd465e6"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "83497f9769e3633cab46224eda0878034170efca448b9cfcd7d8795d97233ad2"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.i686-linux-gnu.tar.gz"
[[ZenohC]]
arch = "i686"
git-tree-sha1 = "77f638a52ca13ca7021aa47be8e2185f5d3758b5"
libc = "musl"
os = "linux"

    [[ZenohC.download]]
    sha256 = "b328c88a912163a6e0bf1b8819f36d25e493e72237afd3bbded1f8635b5dabc4"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.i686-linux-musl.tar.gz"
[[ZenohC]]
arch = "powerpc64le"
git-tree-sha1 = "6b76b967806942a3a1b0ffc41d1e5980556735d0"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "fa931e7e85e9549f10dcf01923bd90418190d272d0ba7bc101a6f86a4d4df474"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.powerpc64le-linux-gnu.tar.gz"
[[ZenohC]]
arch = "x86_64"
git-tree-sha1 = "c67dc14e175cd5da24f20f89ad9e140b591dd2f0"
os = "macos"

    [[ZenohC.download]]
    sha256 = "5c64c00583796e19f4cba11d12a29ba8fcda516e4f068c4c28faa3ed8e68591a"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.x86_64-apple-darwin.tar.gz"
[[ZenohC]]
arch = "x86_64"
git-tree-sha1 = "646a046aff0f937064e81fb1f4cbd73872ced755"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "dfbb696d539f4374f9de7efc406ae7e6a4d9ea12413a52a38008ab78acf6bea0"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.x86_64-linux-gnu.tar.gz"
[[ZenohC]]
arch = "x86_64"
git-tree-sha1 = "524cdb424d292234ea2db13a26aca86a6359965c"
libc = "musl"
os = "linux"

    [[ZenohC.download]]
    sha256 = "9f9de18743439201d5650f0863886081ac73ae02c931138e4c8011c27e5bb3b0"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.x86_64-linux-musl.tar.gz"
[[ZenohC]]
arch = "x86_64"
git-tree-sha1 = "e8d2d0fa63ecfa208e6e2724b9a80915a6d30c2d"
os = "windows"

    [[ZenohC.download]]
    sha256 = "b720ffe173ad1c97fa7c5cf656b3a1cfa4d368a9a06821e709665a028f0bc565"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.4.0+0/ZenohC.v1.4.0.x86_64-w64-mingw32.tar.gz"
