[[ZenohC]]
arch = "aarch64"
git-tree-sha1 = "a3eda92584fe1ecee18acac3db1d32d1142f0136"
os = "macos"

    [[ZenohC.download]]
    sha256 = "1312b21a9ac3a5196b89896cf5a56b85bd144060f675ef142964758763c6e086"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.aarch64-apple-darwin.tar.gz"
[[ZenohC]]
arch = "aarch64"
git-tree-sha1 = "600b761c933044b65ed873d6fbf395331285d092"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "9d22302b7947a89818f5ed3a7f5e9b128321ccc609a5f7bf233c25935c4041a0"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.aarch64-linux-gnu.tar.gz"
[[ZenohC]]
arch = "aarch64"
git-tree-sha1 = "f663812643c080007ba7749c543de87f2ee635b1"
libc = "musl"
os = "linux"

    [[ZenohC.download]]
    sha256 = "734e9eedf3517dd68ae051bb923faa44b71e12eed2b636171a5a9f54a5a51ce4"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.aarch64-linux-musl.tar.gz"
[[ZenohC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ee221df826501b72e29eaafdde522411a97793eb"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "26dce8a5304887d6d4984c08cbc9882e1fb226702ad9a83ff9b1127b978a184a"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.armv6l-linux-gnueabihf.tar.gz"
[[ZenohC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9a075643d31565faa90a79cfbf4c6377c3641917"
libc = "musl"
os = "linux"

    [[ZenohC.download]]
    sha256 = "6405c8e78aec647fac026a202f03d56fca0b5ce312dae7bfa44449a61f73d17b"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.armv6l-linux-musleabihf.tar.gz"
[[ZenohC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "91a2eb72e9138a02096b56529b2fa88018cafc7d"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "a76e8e8fc67681f0406e9084449a10ee71890d1a68ab12c21e3afb047605c47d"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.armv7l-linux-gnueabihf.tar.gz"
[[ZenohC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "073d23e2373e7424cd7ba37e3bead124bfc00676"
libc = "musl"
os = "linux"

    [[ZenohC.download]]
    sha256 = "19d275ada148195e65341ccd2f3a9fe41e10593f316355f595906d65bac6f04a"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.armv7l-linux-musleabihf.tar.gz"
[[ZenohC]]
arch = "i686"
git-tree-sha1 = "4dab7d02b7ba9b8c103b2ef48afd0d66c33930af"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "54a149288d7e8528c319e0f75c2215babb3bed71c09c074348c54fd61beeaea1"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.i686-linux-gnu.tar.gz"
[[ZenohC]]
arch = "i686"
git-tree-sha1 = "7e672b78414e33614d5637da7cc0a1000561bedf"
libc = "musl"
os = "linux"

    [[ZenohC.download]]
    sha256 = "3ebb772e2144f7f1e9e30e9fb5a20e25dd61b3d06d4ebfa90146c91f6c3a09e1"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.i686-linux-musl.tar.gz"
[[ZenohC]]
arch = "powerpc64le"
git-tree-sha1 = "0565fb1d64f30c8310933f36a610d1d36eb07bf9"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "327a84ba7bf763f059040ef9a0b21dd706997c35e99ba4122e999c94cc60b727"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.powerpc64le-linux-gnu.tar.gz"
[[ZenohC]]
arch = "x86_64"
git-tree-sha1 = "4b19fc1329f89e5f1495fdfdcf80691f7b328815"
os = "macos"

    [[ZenohC.download]]
    sha256 = "dcea211366449a024d3ea9ca7778a103cf395fea6db07f284d56583d35367420"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.x86_64-apple-darwin.tar.gz"
[[ZenohC]]
arch = "x86_64"
git-tree-sha1 = "7da06d3d5f137f36b66343e27894821178690e78"
libc = "glibc"
os = "linux"

    [[ZenohC.download]]
    sha256 = "087f6a5eebdf06a8ca829fe51a42c32efc769068c61326e733b702ea6559cbeb"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.x86_64-linux-gnu.tar.gz"
[[ZenohC]]
arch = "x86_64"
git-tree-sha1 = "a18d447fb711d6522711b53a87694b41b4047315"
libc = "musl"
os = "linux"

    [[ZenohC.download]]
    sha256 = "a04922f482d785c409d5e42c4933e91406b1ed1ef5a8a037b066e07f42890632"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.x86_64-linux-musl.tar.gz"
[[ZenohC]]
arch = "x86_64"
git-tree-sha1 = "8f44554da7fbc8f28e451b35c6364a6157cb92f1"
os = "windows"

    [[ZenohC.download]]
    sha256 = "4bde58cbd5f8851136675382cb36ceb01dfe0fe65850d3a324e7d688ee27b5ca"
    url = "https://github.com/JuliaBinaryWrappers/ZenohC_jll.jl/releases/download/ZenohC-v1.3.3+0/ZenohC.v1.3.3.x86_64-w64-mingw32.tar.gz"
